title: "Strevlan Limited" # the name of your site, e.g. ACME Corp.
email: info@cic.org
description: >- # this means to ignore newlines until "baseurl:"
  To provide a platform that allows for growth, development and integration of social prescribing/Self-Care
  and the VCS in West London across sectors including Local Authority, NHS, and other bodies..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aonomike.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: strevlan
github_username:  aonomike
sass:
    load_paths:
        - _sass
        - node_modules

exclude: []


